version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/github_action

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
    mode: 755
    
hooks:
  BeforeInstall:
    - location: deploy-before.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/deploy.sh
      runas: ubuntu
