version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aloha-spring-backend2/
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
    mode: 755
    
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      runas: ubuntu
