server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/inha-plus-db
    driver-class-name: org.h2.Driver
    username: test
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create