server:
  port: 8080

connection:
  iclass-init-url: "https://learn.inha.ac.kr/login/index.php"
  iclass-video-url: "https://learn.inha.ac.kr/mod/vod/index.php?id="
  iclass-quiz-url: "https://learn.inha.ac.kr/mod/quiz/index.php?id="
  iclass-assign-url: "https://learn.inha.ac.kr/mod/assign/index.php?id="
  iclass-attend-url: "https://learn.inha.ac.kr/report/ubcompletion/user_progress_a.php?id="


