name: Deploy Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Verify Build Output
      run: ls -lh build/libs/

    - name: Compress Build Files
      run: |
        mkdir -p deploy
        cp build/libs/*.jar deploy
        tar -czf deploy.tar.gz -C deploy .
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Transfer Build Files
      run: |
        scp deploy.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/deploy.tar.gz
    - name: Deploy on Server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/${{ secrets.SSH_USER }}
          tar -xzf deploy.tar.gz
          mv app.jar ${{ secrets.APP_PATH }}/app.jar
          rm deploy.tar.gz
          sudo systemctl restart aloha  # systemd를 사용하여 서비스 재시작
        EOF
