name: CI CD

on:
  push:
    branches: ['master']

env:
  LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
  LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
  LIGHTSAIL_USERNAME: bitnami
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout release
        uses: actions/checkout@v3

      - name: compress
        run: tar cvfz ./$GITHUB_SHA.tar.gz *
        shell: bash
        
      # AWS 인증을 시작합니다.
      - name: AWS 인증하기
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: AWS Lightsail에 연결되었는지 확인
        run: aws configure list

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://lightsail-github-action-cicd

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name aloha-time
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name AlohaTimeDeploymentGrouop
          --s3-location bucket=lightsail-github-action-cicd,bundleType=tgz,key=$GITHUB_SHA.tar.gz

